#! /bin/bash
echo "   Static hostname: $(hostname)"
echo "         Icon name: computer"
echo "        Machine ID: $(EARNAPP_ID)"
echo "           Boot ID: $(EARNAPP_ID)"
echo "  Operating System: Debian GNU/Linux 11 (bullseye)"
echo "            Kernel: $(uname -s -r)"
echo "      Architecture: $(uname -m | sed s/_/-/g)"
